#     ___   ______
#    /   | / ____/
#   / /| |/ /      By jonagamerpro1234
#  / ___ / /___    Version 1.7.0-b20
# /_/  |_\____/    Thanks for using AdvancedChat <3
#
# ● AdvancedChat is an easy-to-use plugin that will help you customize the chat on your server to make it look its best. It will also have a customization system by groups and among other functions more...
#
# ● Spigot: https://www.spigotmc.org/resources/advancedchat-1-7-x-1-17-x.83889/
# ● Songoda: https://songoda.com/marketplace/product/advancedchat-chat-related.542
# ● Wiki [Work in progress]: https://jonagamerpro1234.gitbook.io/advancedchat/
# ● Discord: https://discord.gg/c5GhQDQCK5
# ● Issue Tracker: https://github.com/jonagamerpro1234/AdvancedChat/issues
# ● Bstast: https://bstats.org/plugin/bukkit/AdvancedChat/8826

# The notification of updates will be disabled if it is false this only disables the notifications when entering the server,
# if it is true, a notification will be sent if there is an update available
# Permission: advancedchat.update
Update: true

# here you can enable or disable the chat to be seen in the console
ShowChatInConsole: true

# This option should only be used if there is a problem with certain functions of the plugin, debug messages will be activated in the console
Debug: false

# Here are all the configurations of the plugin implementations and more
Hooks:

  # Here you can configure everything related to LuckPerms and or deactivate or activate functions
  LuckPerms:

    # This function allows the plugin to detect if the player has changed rank in a period of time defined in the [Tick] section
    AutoUpdateGroup: true

    # here you can define the time that the actions are automatically executed [Default = 600], 600 tick = 30 sec
    Tick: 600

  # Here you can define the discord channel where the messages from minecraft to discord are seen
  DiscordSRV:

    # Here you can enable or disable this feature
    Enable: true

    # Here is the id of the channel that is used for the chat
    Channel: none

# Here you can customize the chat of your server with the different functions that advancedchat brings
# For more information you can see the wiki: https://jonagamerpro1234.gitbook.io/advancedchat/
ChatFormat:

  # Here you can enable or disable this feature
  Enable: true

  # Here you define the chat format for all players.
  Format: "&a[YouCustomChat] &e{player}&8>"

  # The chat type is to use the three types that exist which are, normal | group | comp(compatibility)
  # > normal: use the chat customization that the plugin brings
  # > group:
  # > comp:
  Chat-Type: normal

  # This section allows you to modify the hover events in the chat
  HoverEvent:

    # Here you can enable or disable this feature
    Enable: true

    #
    Hover:
      - ""
      - ""
      - ""

  #
  ClickEvent:

    # Here you can enable or disable this feature
    Enable: true

    #
    Actions:
      - "run= msg {player} test"
      - "suggest= /helpop"
      - "openurl= https://minecraft.net"

#
ClearChat:

  # Here you can enable or disable this feature
  Enable: true

  # you can activate the automatic cleaning of the chat according to the number of ticks
  AutoClear: true

  # With this function you can make the staff is not affected by the clearchat
  # Permission: advancedchat.clearchat.bypass
  ByPassStaff: false

  # Here you can define the first ticks that are executed when starting the server
  start-tick: 6000

  #
  tick: 24000

# Do not change
File-Version: 1